// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: home_relay.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_home_5frelay_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_home_5frelay_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "home_chat.pb.h"
#include "home_account.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_home_5frelay_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_home_5frelay_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_home_5frelay_2eproto;
namespace im_home_proto {
class AgreeApplyFriendsToReceiver;
struct AgreeApplyFriendsToReceiverDefaultTypeInternal;
extern AgreeApplyFriendsToReceiverDefaultTypeInternal _AgreeApplyFriendsToReceiver_default_instance_;
class ApplyFriendsToReceiver;
struct ApplyFriendsToReceiverDefaultTypeInternal;
extern ApplyFriendsToReceiverDefaultTypeInternal _ApplyFriendsToReceiver_default_instance_;
class ChatSingleToReceiver;
struct ChatSingleToReceiverDefaultTypeInternal;
extern ChatSingleToReceiverDefaultTypeInternal _ChatSingleToReceiver_default_instance_;
class NotifyUnReadMessage;
struct NotifyUnReadMessageDefaultTypeInternal;
extern NotifyUnReadMessageDefaultTypeInternal _NotifyUnReadMessage_default_instance_;
class NotifyUserMessage;
struct NotifyUserMessageDefaultTypeInternal;
extern NotifyUserMessageDefaultTypeInternal _NotifyUserMessage_default_instance_;
}  // namespace im_home_proto
PROTOBUF_NAMESPACE_OPEN
template<> ::im_home_proto::AgreeApplyFriendsToReceiver* Arena::CreateMaybeMessage<::im_home_proto::AgreeApplyFriendsToReceiver>(Arena*);
template<> ::im_home_proto::ApplyFriendsToReceiver* Arena::CreateMaybeMessage<::im_home_proto::ApplyFriendsToReceiver>(Arena*);
template<> ::im_home_proto::ChatSingleToReceiver* Arena::CreateMaybeMessage<::im_home_proto::ChatSingleToReceiver>(Arena*);
template<> ::im_home_proto::NotifyUnReadMessage* Arena::CreateMaybeMessage<::im_home_proto::NotifyUnReadMessage>(Arena*);
template<> ::im_home_proto::NotifyUserMessage* Arena::CreateMaybeMessage<::im_home_proto::NotifyUserMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace im_home_proto {

// ===================================================================

class ChatSingleToReceiver final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:im_home_proto.ChatSingleToReceiver) */ {
 public:
  inline ChatSingleToReceiver() : ChatSingleToReceiver(nullptr) {}
  ~ChatSingleToReceiver() override;
  explicit PROTOBUF_CONSTEXPR ChatSingleToReceiver(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatSingleToReceiver(const ChatSingleToReceiver& from);
  ChatSingleToReceiver(ChatSingleToReceiver&& from) noexcept
    : ChatSingleToReceiver() {
    *this = ::std::move(from);
  }

  inline ChatSingleToReceiver& operator=(const ChatSingleToReceiver& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatSingleToReceiver& operator=(ChatSingleToReceiver&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatSingleToReceiver& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatSingleToReceiver* internal_default_instance() {
    return reinterpret_cast<const ChatSingleToReceiver*>(
               &_ChatSingleToReceiver_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChatSingleToReceiver& a, ChatSingleToReceiver& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatSingleToReceiver* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatSingleToReceiver* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatSingleToReceiver* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatSingleToReceiver>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatSingleToReceiver& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ChatSingleToReceiver& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatSingleToReceiver* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "im_home_proto.ChatSingleToReceiver";
  }
  protected:
  explicit ChatSingleToReceiver(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
    kSenderInfoFieldNumber = 2,
  };
  // .im_home_proto.ChatMessage Data = 1;
  bool has_data() const;
  private:
  bool _internal_has_data() const;
  public:
  void clear_data();
  const ::im_home_proto::ChatMessage& data() const;
  PROTOBUF_NODISCARD ::im_home_proto::ChatMessage* release_data();
  ::im_home_proto::ChatMessage* mutable_data();
  void set_allocated_data(::im_home_proto::ChatMessage* data);
  private:
  const ::im_home_proto::ChatMessage& _internal_data() const;
  ::im_home_proto::ChatMessage* _internal_mutable_data();
  public:
  void unsafe_arena_set_allocated_data(
      ::im_home_proto::ChatMessage* data);
  ::im_home_proto::ChatMessage* unsafe_arena_release_data();

  // .im_home_proto.UserInfo SenderInfo = 2;
  bool has_senderinfo() const;
  private:
  bool _internal_has_senderinfo() const;
  public:
  void clear_senderinfo();
  const ::im_home_proto::UserInfo& senderinfo() const;
  PROTOBUF_NODISCARD ::im_home_proto::UserInfo* release_senderinfo();
  ::im_home_proto::UserInfo* mutable_senderinfo();
  void set_allocated_senderinfo(::im_home_proto::UserInfo* senderinfo);
  private:
  const ::im_home_proto::UserInfo& _internal_senderinfo() const;
  ::im_home_proto::UserInfo* _internal_mutable_senderinfo();
  public:
  void unsafe_arena_set_allocated_senderinfo(
      ::im_home_proto::UserInfo* senderinfo);
  ::im_home_proto::UserInfo* unsafe_arena_release_senderinfo();

  // @@protoc_insertion_point(class_scope:im_home_proto.ChatSingleToReceiver)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::im_home_proto::ChatMessage* data_;
  ::im_home_proto::UserInfo* senderinfo_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_home_5frelay_2eproto;
};
// -------------------------------------------------------------------

class ApplyFriendsToReceiver final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:im_home_proto.ApplyFriendsToReceiver) */ {
 public:
  inline ApplyFriendsToReceiver() : ApplyFriendsToReceiver(nullptr) {}
  ~ApplyFriendsToReceiver() override;
  explicit PROTOBUF_CONSTEXPR ApplyFriendsToReceiver(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ApplyFriendsToReceiver(const ApplyFriendsToReceiver& from);
  ApplyFriendsToReceiver(ApplyFriendsToReceiver&& from) noexcept
    : ApplyFriendsToReceiver() {
    *this = ::std::move(from);
  }

  inline ApplyFriendsToReceiver& operator=(const ApplyFriendsToReceiver& from) {
    CopyFrom(from);
    return *this;
  }
  inline ApplyFriendsToReceiver& operator=(ApplyFriendsToReceiver&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ApplyFriendsToReceiver& default_instance() {
    return *internal_default_instance();
  }
  static inline const ApplyFriendsToReceiver* internal_default_instance() {
    return reinterpret_cast<const ApplyFriendsToReceiver*>(
               &_ApplyFriendsToReceiver_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ApplyFriendsToReceiver& a, ApplyFriendsToReceiver& b) {
    a.Swap(&b);
  }
  inline void Swap(ApplyFriendsToReceiver* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ApplyFriendsToReceiver* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ApplyFriendsToReceiver* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ApplyFriendsToReceiver>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ApplyFriendsToReceiver& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ApplyFriendsToReceiver& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ApplyFriendsToReceiver* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "im_home_proto.ApplyFriendsToReceiver";
  }
  protected:
  explicit ApplyFriendsToReceiver(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApplyerInfoFieldNumber = 3,
    kSenderIDFieldNumber = 1,
    kReceiverIDFieldNumber = 2,
  };
  // .im_home_proto.UserInfo ApplyerInfo = 3;
  bool has_applyerinfo() const;
  private:
  bool _internal_has_applyerinfo() const;
  public:
  void clear_applyerinfo();
  const ::im_home_proto::UserInfo& applyerinfo() const;
  PROTOBUF_NODISCARD ::im_home_proto::UserInfo* release_applyerinfo();
  ::im_home_proto::UserInfo* mutable_applyerinfo();
  void set_allocated_applyerinfo(::im_home_proto::UserInfo* applyerinfo);
  private:
  const ::im_home_proto::UserInfo& _internal_applyerinfo() const;
  ::im_home_proto::UserInfo* _internal_mutable_applyerinfo();
  public:
  void unsafe_arena_set_allocated_applyerinfo(
      ::im_home_proto::UserInfo* applyerinfo);
  ::im_home_proto::UserInfo* unsafe_arena_release_applyerinfo();

  // int64 SenderID = 1;
  void clear_senderid();
  int64_t senderid() const;
  void set_senderid(int64_t value);
  private:
  int64_t _internal_senderid() const;
  void _internal_set_senderid(int64_t value);
  public:

  // int64 ReceiverID = 2;
  void clear_receiverid();
  int64_t receiverid() const;
  void set_receiverid(int64_t value);
  private:
  int64_t _internal_receiverid() const;
  void _internal_set_receiverid(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:im_home_proto.ApplyFriendsToReceiver)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::im_home_proto::UserInfo* applyerinfo_;
  int64_t senderid_;
  int64_t receiverid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_home_5frelay_2eproto;
};
// -------------------------------------------------------------------

class AgreeApplyFriendsToReceiver final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:im_home_proto.AgreeApplyFriendsToReceiver) */ {
 public:
  inline AgreeApplyFriendsToReceiver() : AgreeApplyFriendsToReceiver(nullptr) {}
  ~AgreeApplyFriendsToReceiver() override;
  explicit PROTOBUF_CONSTEXPR AgreeApplyFriendsToReceiver(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AgreeApplyFriendsToReceiver(const AgreeApplyFriendsToReceiver& from);
  AgreeApplyFriendsToReceiver(AgreeApplyFriendsToReceiver&& from) noexcept
    : AgreeApplyFriendsToReceiver() {
    *this = ::std::move(from);
  }

  inline AgreeApplyFriendsToReceiver& operator=(const AgreeApplyFriendsToReceiver& from) {
    CopyFrom(from);
    return *this;
  }
  inline AgreeApplyFriendsToReceiver& operator=(AgreeApplyFriendsToReceiver&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AgreeApplyFriendsToReceiver& default_instance() {
    return *internal_default_instance();
  }
  static inline const AgreeApplyFriendsToReceiver* internal_default_instance() {
    return reinterpret_cast<const AgreeApplyFriendsToReceiver*>(
               &_AgreeApplyFriendsToReceiver_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AgreeApplyFriendsToReceiver& a, AgreeApplyFriendsToReceiver& b) {
    a.Swap(&b);
  }
  inline void Swap(AgreeApplyFriendsToReceiver* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AgreeApplyFriendsToReceiver* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AgreeApplyFriendsToReceiver* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AgreeApplyFriendsToReceiver>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AgreeApplyFriendsToReceiver& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const AgreeApplyFriendsToReceiver& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AgreeApplyFriendsToReceiver* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "im_home_proto.AgreeApplyFriendsToReceiver";
  }
  protected:
  explicit AgreeApplyFriendsToReceiver(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSenderIDFieldNumber = 1,
    kReceiverIDFieldNumber = 2,
  };
  // int64 SenderID = 1;
  void clear_senderid();
  int64_t senderid() const;
  void set_senderid(int64_t value);
  private:
  int64_t _internal_senderid() const;
  void _internal_set_senderid(int64_t value);
  public:

  // int64 ReceiverID = 2;
  void clear_receiverid();
  int64_t receiverid() const;
  void set_receiverid(int64_t value);
  private:
  int64_t _internal_receiverid() const;
  void _internal_set_receiverid(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:im_home_proto.AgreeApplyFriendsToReceiver)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int64_t senderid_;
  int64_t receiverid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_home_5frelay_2eproto;
};
// -------------------------------------------------------------------

class NotifyUserMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:im_home_proto.NotifyUserMessage) */ {
 public:
  inline NotifyUserMessage() : NotifyUserMessage(nullptr) {}
  ~NotifyUserMessage() override;
  explicit PROTOBUF_CONSTEXPR NotifyUserMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NotifyUserMessage(const NotifyUserMessage& from);
  NotifyUserMessage(NotifyUserMessage&& from) noexcept
    : NotifyUserMessage() {
    *this = ::std::move(from);
  }

  inline NotifyUserMessage& operator=(const NotifyUserMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline NotifyUserMessage& operator=(NotifyUserMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NotifyUserMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const NotifyUserMessage* internal_default_instance() {
    return reinterpret_cast<const NotifyUserMessage*>(
               &_NotifyUserMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(NotifyUserMessage& a, NotifyUserMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(NotifyUserMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NotifyUserMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NotifyUserMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NotifyUserMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NotifyUserMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const NotifyUserMessage& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NotifyUserMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "im_home_proto.NotifyUserMessage";
  }
  protected:
  explicit NotifyUserMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUnReadSingleChatFieldNumber = 1,
  };
  // repeated .im_home_proto.NotifyUnReadMessage UnReadSingleChat = 1;
  int unreadsinglechat_size() const;
  private:
  int _internal_unreadsinglechat_size() const;
  public:
  void clear_unreadsinglechat();
  ::im_home_proto::NotifyUnReadMessage* mutable_unreadsinglechat(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::im_home_proto::NotifyUnReadMessage >*
      mutable_unreadsinglechat();
  private:
  const ::im_home_proto::NotifyUnReadMessage& _internal_unreadsinglechat(int index) const;
  ::im_home_proto::NotifyUnReadMessage* _internal_add_unreadsinglechat();
  public:
  const ::im_home_proto::NotifyUnReadMessage& unreadsinglechat(int index) const;
  ::im_home_proto::NotifyUnReadMessage* add_unreadsinglechat();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::im_home_proto::NotifyUnReadMessage >&
      unreadsinglechat() const;

  // @@protoc_insertion_point(class_scope:im_home_proto.NotifyUserMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::im_home_proto::NotifyUnReadMessage > unreadsinglechat_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_home_5frelay_2eproto;
};
// -------------------------------------------------------------------

class NotifyUnReadMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:im_home_proto.NotifyUnReadMessage) */ {
 public:
  inline NotifyUnReadMessage() : NotifyUnReadMessage(nullptr) {}
  ~NotifyUnReadMessage() override;
  explicit PROTOBUF_CONSTEXPR NotifyUnReadMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NotifyUnReadMessage(const NotifyUnReadMessage& from);
  NotifyUnReadMessage(NotifyUnReadMessage&& from) noexcept
    : NotifyUnReadMessage() {
    *this = ::std::move(from);
  }

  inline NotifyUnReadMessage& operator=(const NotifyUnReadMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline NotifyUnReadMessage& operator=(NotifyUnReadMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NotifyUnReadMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const NotifyUnReadMessage* internal_default_instance() {
    return reinterpret_cast<const NotifyUnReadMessage*>(
               &_NotifyUnReadMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(NotifyUnReadMessage& a, NotifyUnReadMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(NotifyUnReadMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NotifyUnReadMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NotifyUnReadMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NotifyUnReadMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NotifyUnReadMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const NotifyUnReadMessage& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NotifyUnReadMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "im_home_proto.NotifyUnReadMessage";
  }
  protected:
  explicit NotifyUnReadMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserFieldNumber = 1,
    kUnReadMessageSumFieldNumber = 2,
  };
  // .im_home_proto.UserInfo User = 1;
  bool has_user() const;
  private:
  bool _internal_has_user() const;
  public:
  void clear_user();
  const ::im_home_proto::UserInfo& user() const;
  PROTOBUF_NODISCARD ::im_home_proto::UserInfo* release_user();
  ::im_home_proto::UserInfo* mutable_user();
  void set_allocated_user(::im_home_proto::UserInfo* user);
  private:
  const ::im_home_proto::UserInfo& _internal_user() const;
  ::im_home_proto::UserInfo* _internal_mutable_user();
  public:
  void unsafe_arena_set_allocated_user(
      ::im_home_proto::UserInfo* user);
  ::im_home_proto::UserInfo* unsafe_arena_release_user();

  // int32 UnReadMessageSum = 2;
  void clear_unreadmessagesum();
  int32_t unreadmessagesum() const;
  void set_unreadmessagesum(int32_t value);
  private:
  int32_t _internal_unreadmessagesum() const;
  void _internal_set_unreadmessagesum(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:im_home_proto.NotifyUnReadMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::im_home_proto::UserInfo* user_;
  int32_t unreadmessagesum_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_home_5frelay_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChatSingleToReceiver

// .im_home_proto.ChatMessage Data = 1;
inline bool ChatSingleToReceiver::_internal_has_data() const {
  return this != internal_default_instance() && data_ != nullptr;
}
inline bool ChatSingleToReceiver::has_data() const {
  return _internal_has_data();
}
inline const ::im_home_proto::ChatMessage& ChatSingleToReceiver::_internal_data() const {
  const ::im_home_proto::ChatMessage* p = data_;
  return p != nullptr ? *p : reinterpret_cast<const ::im_home_proto::ChatMessage&>(
      ::im_home_proto::_ChatMessage_default_instance_);
}
inline const ::im_home_proto::ChatMessage& ChatSingleToReceiver::data() const {
  // @@protoc_insertion_point(field_get:im_home_proto.ChatSingleToReceiver.Data)
  return _internal_data();
}
inline void ChatSingleToReceiver::unsafe_arena_set_allocated_data(
    ::im_home_proto::ChatMessage* data) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(data_);
  }
  data_ = data;
  if (data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:im_home_proto.ChatSingleToReceiver.Data)
}
inline ::im_home_proto::ChatMessage* ChatSingleToReceiver::release_data() {
  
  ::im_home_proto::ChatMessage* temp = data_;
  data_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::im_home_proto::ChatMessage* ChatSingleToReceiver::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_release:im_home_proto.ChatSingleToReceiver.Data)
  
  ::im_home_proto::ChatMessage* temp = data_;
  data_ = nullptr;
  return temp;
}
inline ::im_home_proto::ChatMessage* ChatSingleToReceiver::_internal_mutable_data() {
  
  if (data_ == nullptr) {
    auto* p = CreateMaybeMessage<::im_home_proto::ChatMessage>(GetArenaForAllocation());
    data_ = p;
  }
  return data_;
}
inline ::im_home_proto::ChatMessage* ChatSingleToReceiver::mutable_data() {
  ::im_home_proto::ChatMessage* _msg = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:im_home_proto.ChatSingleToReceiver.Data)
  return _msg;
}
inline void ChatSingleToReceiver::set_allocated_data(::im_home_proto::ChatMessage* data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(data_);
  }
  if (data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(data));
    if (message_arena != submessage_arena) {
      data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, data, submessage_arena);
    }
    
  } else {
    
  }
  data_ = data;
  // @@protoc_insertion_point(field_set_allocated:im_home_proto.ChatSingleToReceiver.Data)
}

// .im_home_proto.UserInfo SenderInfo = 2;
inline bool ChatSingleToReceiver::_internal_has_senderinfo() const {
  return this != internal_default_instance() && senderinfo_ != nullptr;
}
inline bool ChatSingleToReceiver::has_senderinfo() const {
  return _internal_has_senderinfo();
}
inline const ::im_home_proto::UserInfo& ChatSingleToReceiver::_internal_senderinfo() const {
  const ::im_home_proto::UserInfo* p = senderinfo_;
  return p != nullptr ? *p : reinterpret_cast<const ::im_home_proto::UserInfo&>(
      ::im_home_proto::_UserInfo_default_instance_);
}
inline const ::im_home_proto::UserInfo& ChatSingleToReceiver::senderinfo() const {
  // @@protoc_insertion_point(field_get:im_home_proto.ChatSingleToReceiver.SenderInfo)
  return _internal_senderinfo();
}
inline void ChatSingleToReceiver::unsafe_arena_set_allocated_senderinfo(
    ::im_home_proto::UserInfo* senderinfo) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(senderinfo_);
  }
  senderinfo_ = senderinfo;
  if (senderinfo) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:im_home_proto.ChatSingleToReceiver.SenderInfo)
}
inline ::im_home_proto::UserInfo* ChatSingleToReceiver::release_senderinfo() {
  
  ::im_home_proto::UserInfo* temp = senderinfo_;
  senderinfo_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::im_home_proto::UserInfo* ChatSingleToReceiver::unsafe_arena_release_senderinfo() {
  // @@protoc_insertion_point(field_release:im_home_proto.ChatSingleToReceiver.SenderInfo)
  
  ::im_home_proto::UserInfo* temp = senderinfo_;
  senderinfo_ = nullptr;
  return temp;
}
inline ::im_home_proto::UserInfo* ChatSingleToReceiver::_internal_mutable_senderinfo() {
  
  if (senderinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::im_home_proto::UserInfo>(GetArenaForAllocation());
    senderinfo_ = p;
  }
  return senderinfo_;
}
inline ::im_home_proto::UserInfo* ChatSingleToReceiver::mutable_senderinfo() {
  ::im_home_proto::UserInfo* _msg = _internal_mutable_senderinfo();
  // @@protoc_insertion_point(field_mutable:im_home_proto.ChatSingleToReceiver.SenderInfo)
  return _msg;
}
inline void ChatSingleToReceiver::set_allocated_senderinfo(::im_home_proto::UserInfo* senderinfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(senderinfo_);
  }
  if (senderinfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(senderinfo));
    if (message_arena != submessage_arena) {
      senderinfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, senderinfo, submessage_arena);
    }
    
  } else {
    
  }
  senderinfo_ = senderinfo;
  // @@protoc_insertion_point(field_set_allocated:im_home_proto.ChatSingleToReceiver.SenderInfo)
}

// -------------------------------------------------------------------

// ApplyFriendsToReceiver

// int64 SenderID = 1;
inline void ApplyFriendsToReceiver::clear_senderid() {
  senderid_ = int64_t{0};
}
inline int64_t ApplyFriendsToReceiver::_internal_senderid() const {
  return senderid_;
}
inline int64_t ApplyFriendsToReceiver::senderid() const {
  // @@protoc_insertion_point(field_get:im_home_proto.ApplyFriendsToReceiver.SenderID)
  return _internal_senderid();
}
inline void ApplyFriendsToReceiver::_internal_set_senderid(int64_t value) {
  
  senderid_ = value;
}
inline void ApplyFriendsToReceiver::set_senderid(int64_t value) {
  _internal_set_senderid(value);
  // @@protoc_insertion_point(field_set:im_home_proto.ApplyFriendsToReceiver.SenderID)
}

// int64 ReceiverID = 2;
inline void ApplyFriendsToReceiver::clear_receiverid() {
  receiverid_ = int64_t{0};
}
inline int64_t ApplyFriendsToReceiver::_internal_receiverid() const {
  return receiverid_;
}
inline int64_t ApplyFriendsToReceiver::receiverid() const {
  // @@protoc_insertion_point(field_get:im_home_proto.ApplyFriendsToReceiver.ReceiverID)
  return _internal_receiverid();
}
inline void ApplyFriendsToReceiver::_internal_set_receiverid(int64_t value) {
  
  receiverid_ = value;
}
inline void ApplyFriendsToReceiver::set_receiverid(int64_t value) {
  _internal_set_receiverid(value);
  // @@protoc_insertion_point(field_set:im_home_proto.ApplyFriendsToReceiver.ReceiverID)
}

// .im_home_proto.UserInfo ApplyerInfo = 3;
inline bool ApplyFriendsToReceiver::_internal_has_applyerinfo() const {
  return this != internal_default_instance() && applyerinfo_ != nullptr;
}
inline bool ApplyFriendsToReceiver::has_applyerinfo() const {
  return _internal_has_applyerinfo();
}
inline const ::im_home_proto::UserInfo& ApplyFriendsToReceiver::_internal_applyerinfo() const {
  const ::im_home_proto::UserInfo* p = applyerinfo_;
  return p != nullptr ? *p : reinterpret_cast<const ::im_home_proto::UserInfo&>(
      ::im_home_proto::_UserInfo_default_instance_);
}
inline const ::im_home_proto::UserInfo& ApplyFriendsToReceiver::applyerinfo() const {
  // @@protoc_insertion_point(field_get:im_home_proto.ApplyFriendsToReceiver.ApplyerInfo)
  return _internal_applyerinfo();
}
inline void ApplyFriendsToReceiver::unsafe_arena_set_allocated_applyerinfo(
    ::im_home_proto::UserInfo* applyerinfo) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(applyerinfo_);
  }
  applyerinfo_ = applyerinfo;
  if (applyerinfo) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:im_home_proto.ApplyFriendsToReceiver.ApplyerInfo)
}
inline ::im_home_proto::UserInfo* ApplyFriendsToReceiver::release_applyerinfo() {
  
  ::im_home_proto::UserInfo* temp = applyerinfo_;
  applyerinfo_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::im_home_proto::UserInfo* ApplyFriendsToReceiver::unsafe_arena_release_applyerinfo() {
  // @@protoc_insertion_point(field_release:im_home_proto.ApplyFriendsToReceiver.ApplyerInfo)
  
  ::im_home_proto::UserInfo* temp = applyerinfo_;
  applyerinfo_ = nullptr;
  return temp;
}
inline ::im_home_proto::UserInfo* ApplyFriendsToReceiver::_internal_mutable_applyerinfo() {
  
  if (applyerinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::im_home_proto::UserInfo>(GetArenaForAllocation());
    applyerinfo_ = p;
  }
  return applyerinfo_;
}
inline ::im_home_proto::UserInfo* ApplyFriendsToReceiver::mutable_applyerinfo() {
  ::im_home_proto::UserInfo* _msg = _internal_mutable_applyerinfo();
  // @@protoc_insertion_point(field_mutable:im_home_proto.ApplyFriendsToReceiver.ApplyerInfo)
  return _msg;
}
inline void ApplyFriendsToReceiver::set_allocated_applyerinfo(::im_home_proto::UserInfo* applyerinfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(applyerinfo_);
  }
  if (applyerinfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(applyerinfo));
    if (message_arena != submessage_arena) {
      applyerinfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, applyerinfo, submessage_arena);
    }
    
  } else {
    
  }
  applyerinfo_ = applyerinfo;
  // @@protoc_insertion_point(field_set_allocated:im_home_proto.ApplyFriendsToReceiver.ApplyerInfo)
}

// -------------------------------------------------------------------

// AgreeApplyFriendsToReceiver

// int64 SenderID = 1;
inline void AgreeApplyFriendsToReceiver::clear_senderid() {
  senderid_ = int64_t{0};
}
inline int64_t AgreeApplyFriendsToReceiver::_internal_senderid() const {
  return senderid_;
}
inline int64_t AgreeApplyFriendsToReceiver::senderid() const {
  // @@protoc_insertion_point(field_get:im_home_proto.AgreeApplyFriendsToReceiver.SenderID)
  return _internal_senderid();
}
inline void AgreeApplyFriendsToReceiver::_internal_set_senderid(int64_t value) {
  
  senderid_ = value;
}
inline void AgreeApplyFriendsToReceiver::set_senderid(int64_t value) {
  _internal_set_senderid(value);
  // @@protoc_insertion_point(field_set:im_home_proto.AgreeApplyFriendsToReceiver.SenderID)
}

// int64 ReceiverID = 2;
inline void AgreeApplyFriendsToReceiver::clear_receiverid() {
  receiverid_ = int64_t{0};
}
inline int64_t AgreeApplyFriendsToReceiver::_internal_receiverid() const {
  return receiverid_;
}
inline int64_t AgreeApplyFriendsToReceiver::receiverid() const {
  // @@protoc_insertion_point(field_get:im_home_proto.AgreeApplyFriendsToReceiver.ReceiverID)
  return _internal_receiverid();
}
inline void AgreeApplyFriendsToReceiver::_internal_set_receiverid(int64_t value) {
  
  receiverid_ = value;
}
inline void AgreeApplyFriendsToReceiver::set_receiverid(int64_t value) {
  _internal_set_receiverid(value);
  // @@protoc_insertion_point(field_set:im_home_proto.AgreeApplyFriendsToReceiver.ReceiverID)
}

// -------------------------------------------------------------------

// NotifyUserMessage

// repeated .im_home_proto.NotifyUnReadMessage UnReadSingleChat = 1;
inline int NotifyUserMessage::_internal_unreadsinglechat_size() const {
  return unreadsinglechat_.size();
}
inline int NotifyUserMessage::unreadsinglechat_size() const {
  return _internal_unreadsinglechat_size();
}
inline void NotifyUserMessage::clear_unreadsinglechat() {
  unreadsinglechat_.Clear();
}
inline ::im_home_proto::NotifyUnReadMessage* NotifyUserMessage::mutable_unreadsinglechat(int index) {
  // @@protoc_insertion_point(field_mutable:im_home_proto.NotifyUserMessage.UnReadSingleChat)
  return unreadsinglechat_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::im_home_proto::NotifyUnReadMessage >*
NotifyUserMessage::mutable_unreadsinglechat() {
  // @@protoc_insertion_point(field_mutable_list:im_home_proto.NotifyUserMessage.UnReadSingleChat)
  return &unreadsinglechat_;
}
inline const ::im_home_proto::NotifyUnReadMessage& NotifyUserMessage::_internal_unreadsinglechat(int index) const {
  return unreadsinglechat_.Get(index);
}
inline const ::im_home_proto::NotifyUnReadMessage& NotifyUserMessage::unreadsinglechat(int index) const {
  // @@protoc_insertion_point(field_get:im_home_proto.NotifyUserMessage.UnReadSingleChat)
  return _internal_unreadsinglechat(index);
}
inline ::im_home_proto::NotifyUnReadMessage* NotifyUserMessage::_internal_add_unreadsinglechat() {
  return unreadsinglechat_.Add();
}
inline ::im_home_proto::NotifyUnReadMessage* NotifyUserMessage::add_unreadsinglechat() {
  ::im_home_proto::NotifyUnReadMessage* _add = _internal_add_unreadsinglechat();
  // @@protoc_insertion_point(field_add:im_home_proto.NotifyUserMessage.UnReadSingleChat)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::im_home_proto::NotifyUnReadMessage >&
NotifyUserMessage::unreadsinglechat() const {
  // @@protoc_insertion_point(field_list:im_home_proto.NotifyUserMessage.UnReadSingleChat)
  return unreadsinglechat_;
}

// -------------------------------------------------------------------

// NotifyUnReadMessage

// .im_home_proto.UserInfo User = 1;
inline bool NotifyUnReadMessage::_internal_has_user() const {
  return this != internal_default_instance() && user_ != nullptr;
}
inline bool NotifyUnReadMessage::has_user() const {
  return _internal_has_user();
}
inline const ::im_home_proto::UserInfo& NotifyUnReadMessage::_internal_user() const {
  const ::im_home_proto::UserInfo* p = user_;
  return p != nullptr ? *p : reinterpret_cast<const ::im_home_proto::UserInfo&>(
      ::im_home_proto::_UserInfo_default_instance_);
}
inline const ::im_home_proto::UserInfo& NotifyUnReadMessage::user() const {
  // @@protoc_insertion_point(field_get:im_home_proto.NotifyUnReadMessage.User)
  return _internal_user();
}
inline void NotifyUnReadMessage::unsafe_arena_set_allocated_user(
    ::im_home_proto::UserInfo* user) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(user_);
  }
  user_ = user;
  if (user) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:im_home_proto.NotifyUnReadMessage.User)
}
inline ::im_home_proto::UserInfo* NotifyUnReadMessage::release_user() {
  
  ::im_home_proto::UserInfo* temp = user_;
  user_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::im_home_proto::UserInfo* NotifyUnReadMessage::unsafe_arena_release_user() {
  // @@protoc_insertion_point(field_release:im_home_proto.NotifyUnReadMessage.User)
  
  ::im_home_proto::UserInfo* temp = user_;
  user_ = nullptr;
  return temp;
}
inline ::im_home_proto::UserInfo* NotifyUnReadMessage::_internal_mutable_user() {
  
  if (user_ == nullptr) {
    auto* p = CreateMaybeMessage<::im_home_proto::UserInfo>(GetArenaForAllocation());
    user_ = p;
  }
  return user_;
}
inline ::im_home_proto::UserInfo* NotifyUnReadMessage::mutable_user() {
  ::im_home_proto::UserInfo* _msg = _internal_mutable_user();
  // @@protoc_insertion_point(field_mutable:im_home_proto.NotifyUnReadMessage.User)
  return _msg;
}
inline void NotifyUnReadMessage::set_allocated_user(::im_home_proto::UserInfo* user) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(user_);
  }
  if (user) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(user));
    if (message_arena != submessage_arena) {
      user = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, user, submessage_arena);
    }
    
  } else {
    
  }
  user_ = user;
  // @@protoc_insertion_point(field_set_allocated:im_home_proto.NotifyUnReadMessage.User)
}

// int32 UnReadMessageSum = 2;
inline void NotifyUnReadMessage::clear_unreadmessagesum() {
  unreadmessagesum_ = 0;
}
inline int32_t NotifyUnReadMessage::_internal_unreadmessagesum() const {
  return unreadmessagesum_;
}
inline int32_t NotifyUnReadMessage::unreadmessagesum() const {
  // @@protoc_insertion_point(field_get:im_home_proto.NotifyUnReadMessage.UnReadMessageSum)
  return _internal_unreadmessagesum();
}
inline void NotifyUnReadMessage::_internal_set_unreadmessagesum(int32_t value) {
  
  unreadmessagesum_ = value;
}
inline void NotifyUnReadMessage::set_unreadmessagesum(int32_t value) {
  _internal_set_unreadmessagesum(value);
  // @@protoc_insertion_point(field_set:im_home_proto.NotifyUnReadMessage.UnReadMessageSum)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace im_home_proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_home_5frelay_2eproto
